runtime: nodejs10
service: default

handlers:
- url: /
  static_files: dist/browser/index.html
  upload: dist/browser/index.html

- url: /json/(.*\.json)$
  static_files: dist/browser/json/\1
  upload: dist/browser/json/(.*)

- url: /(.*)
  static_files: dist/browser/\1
  upload: dist/browser/(.*)
